
server:
  port: 1314

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:\codeWorkSpace\otinya\otinya.db
    username:
    passowrd:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS